#!/usr/bin/env bash
#PBS -l walltime=05:50:05
#PBS -l mem=5gb
#PBS -N NormExp1HsWV
#PBS -m n
# param chosen for daily production S1A + S1B in a row
echo "Hello ${1}"
#pybin=/home1/datawork/agrouaze/conda_envs2/envs/xsar_gdal3.3_v2/bin/python #dedicated env for Quach 2020 exploit
pybin=/appli/conda-env/jupyterhub-tensorflow/bin/python
export PYTHONPATH=/home1/datahome/agrouaze/git/mpc/data_collect
export PYTHONPATH=/home1/datahome/agrouaze/git/osm_landmask_distancecoast:$PYTHONPATH
export PYTHONPATH=/home1/datahome/agrouaze/git/sar_hs_nn:$PYTHONPATH
export PYTHONPATH=/home1/datahome/agrouaze/git/sar_hs_nn/sarhspredictor:$PYTHONPATH
# pyexe=/home1/datahome/agrouaze/git/sar_hs_nn/sarhspredictor/bin/split_aggregated_into_groups.py
# $pybin $pyexe
pyexe=/home1/datahome/agrouaze/git/sar_hs_nn/sarhspredictor/lib/normalization_inputs_exp1.py # for all the high level features + spec from OCN and SLC
#pyexe=/home1/datahome/agrouaze/git/sar_hs_nn/sarhspredictor/lib/normalization_inputs_exp1v4.py # for less high level features + spec from SLC onlu
pyexe=/home1/datahome/agrouaze/git/sar_hs_nn/sarhspredictor/lib/normalization_inputs_exp1v4_nc_outputs.py # same as above but in netCDF
pyexe=/home1/datahome/agrouaze/git/sar_hs_nn/sarhspredictor/lib/normalization_inputs_exp2.py # data 2019-2022 100% IFREMER SLC
#start stop inputs YYYYMMDD
# redo option added for v7_norm because previous files were with a different normalization
$pybin $pyexe --startdate ${1} --stopdate ${2}
echo end of python script exe
exit 0
