model45path='/home/datawork-cersat-public/cache/project/mpc-sentinel1/analysis/s1_data_analysis/hs_nn/reference_Hs_models/quach2020/model_45.h5'
model45stdpath='/home/datawork-cersat-public/cache/project/mpc-sentinel1/analysis/s1_data_analysis/hs_nn/reference_Hs_models/quach2020/model_45_std_tuned.h5'
model_heteroskedastic_2017='/home/datawork-cersat-public/cache/project/mpc-sentinel1/analysis/s1_data_analysis/hs_nn/reference_Hs_models/quach2020/heteroskedastic_2017.h5'
model_IFR_replication_quach2020_sadowski_release_5feb2021 = '/home/datawork-cersat-public/project/mpc-sentinel1/analysis/s1_data_analysis/hs_nn/reference_Hs_models/quach2020/heteroskedastic_2017_agrouaze.h5'
model_IFR_replication_quach2020_sadowski_release_5feb2021_exp1 = '/home/datawork-cersat-public/project/mpc-sentinel1/analysis/s1_data_analysis/hs_nn/reference_Hs_models/quach2020/exp1_agrouaze.h5'
model_IFR_replication_quach2020_sadowski_release_5feb2021_v2 = '/home/datawork-cersat-public/project/mpc-sentinel1/analysis/s1_data_analysis/hs_nn/reference_Hs_models/quach2020/heteroskedastic_2017_agrouaze_v2.h5'
land_polygon_path = '/home/datawork-cersat-exp/ipf/static/landmask/land_polygons'
land_raster_path = '/home/datawork-cersat-exp/ipf/static/landmask/land_raster.nc'