model45path='/home1/datahome/agrouaze/sources/sentinel1/hs_total/validation_quach2020/model_45.h5'
model45stdpath='/home1/datahome/agrouaze/sources/sentinel1/hs_total/validation_quach2020/model_45_std_tuned.h5'
model_heteroskedastic_2017='/home1/datahome/agrouaze/git/SAR-Wave-Height/models/heteroskedastic_2017.h5'
land_polygon_path = '/home/datawork-cersat-exp/ipf/static/landmask/land_polygons'
land_raster_path = '/home/datawork-cersat-exp/ipf/static/landmask/land_raster.nc'